"""Add payment_id to Order

Revision ID: 0a6e517a89ab
Revises: 
Create Date: 2026-04-08 12:50:57.321272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a6e517a89ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('buy_now', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('payment_id', sa.String(length=100), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=True)
        batch_op.drop_column('payment_method')
        batch_op.drop_column('status')
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.VARCHAR(length=50), nullable=False))
        batch_op.alter_column('address',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('payment_id')
        batch_op.drop_column('buy_now')
        batch_op.drop_column('total')
        batch_op.drop_column('payment')

    # ### end Alembic commands ###
