"""Add payment_method

Revision ID: 518f2736b33d
Revises: 0a6e517a89ab
Create Date: 2026-04-08 12:56:46.658089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '518f2736b33d'
down_revision = '0a6e517a89ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=False))
        batch_op.drop_column('payment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
